//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWM.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog
    {
        public string CatalogID { get; set; }
        public string SellerID { get; set; }
        public string CatalogName { get; set; }
        public int OrderBy { get; set; }
        public bool Deleted { get; set; }
    }
}
