//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWM.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public string GoodsID { get; set; }
        public string BarCode { get; set; }
        public string Image { get; set; }
        public string Name { get; set; }
        public string Icon { get; set; }
        public decimal PurchasePrice { get; set; }
        public decimal SellingPrice { get; set; }
        public decimal MinSellingPrice { get; set; }
        public string Description { get; set; }
        public int Rating { get; set; }
        public int Stock { get; set; }
        public string Seller { get; set; }
        public bool Deleted { get; set; }
        public bool Visible { get; set; }
        public string CatalogID { get; set; }
    }
}
