//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWM.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public string GoodsID { get; set; }
        public string BarCode { get; set; }
        public string QRCode { get; set; }
        public string FullName { get; set; }
        public string ShortName { get; set; }
        public string PictureURL { get; set; }
        public decimal PurchasePrice { get; set; }
        public decimal SellingPrice { get; set; }
        public decimal MinSellingPrice { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
        public int Stock { get; set; }
        public int SoldOut { get; set; }
    }
}
