//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWM.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string OrderID { get; set; }
        public string SellerID { get; set; }
        public string UserID { get; set; }
        public int OrderStatus { get; set; }
        public System.DateTime Create { get; set; }
        public decimal Payable { get; set; }
        public decimal ActPay { get; set; }
        public string PayOrderID { get; set; }
        public string PayType { get; set; }
        public int OrderIndex { get; set; }
        public decimal TotalPrice { get; set; }
    }
}
