//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWM.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Printer
    {
        public string PrinterID { get; set; }
        public string PrinterType { get; set; }
        public string Name { get; set; }
        public string Desc { get; set; }
        public string ApiURL { get; set; }
    }
}
