//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWM.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller
    {
        public string SellerID { get; set; }
        public string FullName { get; set; }
        public string ShortName { get; set; }
        public string Address { get; set; }
        public string MapURL { get; set; }
        public string LogoURL { get; set; }
        public string OwnerWeixinID { get; set; }
        public string OwnerPhone { get; set; }
        public string OwnerName { get; set; }
        public string OwnerIDNumber { get; set; }
    }
}
