//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWM.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller
    {
        public string SellerID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Bulletin { get; set; }
        public string Avatar { get; set; }
        public int FoodScore { get; set; }
        public float MinPrice { get; set; }
        public int RankRate { get; set; }
        public int RatingCount { get; set; }
        public int Score { get; set; }
        public int SellCount { get; set; }
        public int ServiceScore { get; set; }
        public int TableNumber { get; set; }
        public bool Deleted { get; set; }
        public string PrintID { get; set; }
    }
}
