//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWM.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WeWaiterEntities : DbContext
    {
        public WeWaiterEntities()
            : base("name=WeWaiterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BuyItem> BuyItem { get; set; }
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Seller> Seller { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
